# Site wide configuration
title: pebblestone
description: "\n\n"
logo: favicon.ico # 120x120 px default image used for Twitter summary card
teaser: default.jpg
#locale:
baseurl: /
url: http://dailey007.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name:dailey
  email:pebblestone@qq.com
  twitter:@daileydai
  google:daileyv587@gmail.com
 #   ad-client: 
 #   ad-slot: 
 # bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
#disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
